# Generated by Django 4.1.3 on 2022-11-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_is_admin_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
