# Generated by Django 4.1.3 on 2022-11-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_att',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
