# Generated by Django 4.1.3 on 2022-11-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_added_att'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='added_att',
        ),
    ]
